language: python
python:
  - "3.13"
before_script:
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install lxml
  - pip install pluginbase
  - pip install python-slugify
  - pip install mock
  - pip install psutil
script:
  - coverage run -m py.test --verbose tests/unit
after_success:
  - coveralls --rcfile=.coveragerc
